version: '3.1'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - "elasticsearch"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.3.0
    depends_on:
      - "elasticsearch"
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/

volumes:
  esdata1:
    driver: local

networks:
  default:
    external: 
      name: cidadao

